"""Wing-focused optimizer module (geometry/airfoil/stability domain)."""

from __future__ import annotations

from dataclasses import dataclass
from math import sqrt
from pathlib import Path
import random

from wingopt.aero.model import AeroModel
from wingopt.config.models import EnvironmentScenario, WingGenConfig
from wingopt.geometry.airfoil import AirfoilData, load_airfoil_library
from wingopt.geometry.planform import WingGeometry, compute_planform
from wingopt.stability.model import StabilityAnalyzer
from wingopt.structures.model import StructuresModel
from wingopt.utils.atmosphere import build_atmosphere
from wingopt.utils.units import g_to_kg, kmh_to_ms

G = 9.80665


@dataclass(frozen=True)
class ThrustEnvelope:
    """Propulsion demand envelope generated by wing solution."""

    cruise_speed_ms: float
    max_speed_ms: float
    required_thrust_cruise_n: float
    required_thrust_max_n: float
    required_power_cruise_w: float
    required_power_max_w: float


@dataclass(frozen=True)
class WingCandidate:
    """Wing optimizer candidate output."""

    wingspan_m: float
    root_chord_m: float
    tip_chord_m: float
    sweep_deg: float
    dihedral_deg: float
    root_incidence_deg: float
    tip_incidence_deg: float
    twist_deg: float
    airfoil: str
    cg_fraction_mac: float
    wing_area_m2: float
    aspect_ratio: float
    wing_loading_gdm2: float
    static_margin: float
    lateral_stability_index: float
    trim_elevon_deg: float
    cruise_ld: float
    cruise_cd: float
    stall_speed_kmh: float
    structural_mass_g: float
    total_mass_g: float
    envelope: ThrustEnvelope
    feasible: bool
    score: float


@dataclass(frozen=True)
class AirfoilComparison:
    """Side-by-side comparison metrics for each airfoil candidate."""

    airfoil: str
    evaluated_count: int
    feasible_count: int
    best_score: float
    best_ld: float
    best_static_margin: float
    best_stall_speed_kmh: float


class WingOptimizer:
    """Optimizer over geometry + airfoil + stability variables."""

    def __init__(self, config: WingGenConfig, data_dir: str | Path = "data") -> None:
        self.config = config
        self.data_dir = Path(data_dir)
        self.airfoils = self._load_airfoils()
        self.last_all_candidates: tuple[WingCandidate, ...] = tuple()

    def _load_airfoils(self) -> dict[str, AirfoilData]:
        return load_airfoil_library(
            self.data_dir / "airfoils",
            candidates=self.config.geometry.airfoil_candidates,
        )

    def optimize(self, top_k: int = 8) -> tuple[WingCandidate, ...]:
        """Search wing design space and return top-ranked feasible candidates."""

        rng = random.Random(self.config.optimizer.wing.seed)
        candidates: list[WingCandidate] = []
        max_eval = self.config.optimizer.wing.max_evaluations

        for i in range(max_eval):
            airfoil_name = self.config.geometry.airfoil_candidates[
                i % len(self.config.geometry.airfoil_candidates)
            ]
            wing_cfg = self._sample_geometry(rng)
            candidate = self._evaluate_candidate(wing_cfg=wing_cfg, airfoil_name=airfoil_name)
            if candidate is not None:
                candidates.append(candidate)

        self.last_all_candidates = tuple(candidates)
        ranked = sorted(candidates, key=lambda c: c.score, reverse=True)
        return tuple(ranked[:top_k])

    def airfoil_comparison(self) -> tuple[AirfoilComparison, ...]:
        """Return per-airfoil comparison from the latest optimization call."""
        all_candidates = self.last_all_candidates
        comparison: list[AirfoilComparison] = []
        for airfoil in self.config.geometry.airfoil_candidates:
            group = [candidate for candidate in all_candidates if candidate.airfoil == airfoil]
            if not group:
                comparison.append(
                    AirfoilComparison(
                        airfoil=airfoil,
                        evaluated_count=0,
                        feasible_count=0,
                        best_score=float("-inf"),
                        best_ld=0.0,
                        best_static_margin=0.0,
                        best_stall_speed_kmh=0.0,
                    )
                )
                continue

            feasible = [candidate for candidate in group if candidate.feasible]
            best_pool = feasible if feasible else group
            best = max(best_pool, key=lambda candidate: candidate.score)
            comparison.append(
                AirfoilComparison(
                    airfoil=airfoil,
                    evaluated_count=len(group),
                    feasible_count=len(feasible),
                    best_score=best.score,
                    best_ld=best.cruise_ld,
                    best_static_margin=best.static_margin,
                    best_stall_speed_kmh=best.stall_speed_kmh,
                )
            )

        return tuple(comparison)

    def _sample_geometry(self, rng: random.Random) -> dict[str, float]:
        space = self.config.design_space.wing
        return {
            "wingspan_m": rng.uniform(space.wingspan_m.minimum, space.wingspan_m.maximum),
            "root_chord_m": rng.uniform(space.root_chord_m.minimum, space.root_chord_m.maximum),
            "tip_chord_m": rng.uniform(space.tip_chord_m.minimum, space.tip_chord_m.maximum),
            "sweep_deg": rng.uniform(space.sweep_deg.minimum, space.sweep_deg.maximum),
            "dihedral_deg": rng.uniform(space.dihedral_deg.minimum, space.dihedral_deg.maximum),
            "root_incidence_deg": rng.uniform(
                space.root_incidence_deg.minimum,
                space.root_incidence_deg.maximum,
            ),
            "tip_incidence_deg": rng.uniform(
                space.tip_incidence_deg.minimum,
                space.tip_incidence_deg.maximum,
            ),
            "cg_fraction_mac": rng.uniform(
                space.cg_fraction_mac.minimum,
                space.cg_fraction_mac.maximum,
            ),
        }

    def _evaluate_candidate(self, wing_cfg: dict[str, float], airfoil_name: str) -> WingCandidate | None:
        local_geom = self.config.geometry
        geometry_config = local_geom.__class__(
            wingspan_m=wing_cfg["wingspan_m"],
            root_chord_m=wing_cfg["root_chord_m"],
            tip_chord_m=wing_cfg["tip_chord_m"],
            sweep_deg=wing_cfg["sweep_deg"],
            dihedral_deg=wing_cfg["dihedral_deg"],
            root_incidence_deg=wing_cfg["root_incidence_deg"],
            tip_incidence_deg=wing_cfg["tip_incidence_deg"],
            airfoil=airfoil_name,
            airfoil_candidates=local_geom.airfoil_candidates,
            elevons=local_geom.elevons,
        )

        try:
            geometry: WingGeometry = compute_planform(geometry_config)
            airfoil = self.airfoils[airfoil_name]
        except Exception:
            return None

        cruise_speed = kmh_to_ms(self.config.mission.cruise_speed_kmh)
        max_speed = kmh_to_ms(self.config.mission.max_speed_kmh)
        scenario: EnvironmentScenario = self.config.environment.resolved_scenarios()[0]
        atmosphere = build_atmosphere(
            temperature_c=scenario.temperature_c,
            altitude_m=scenario.altitude_m,
            pressure_pa=scenario.pressure_pa,
            relative_humidity=scenario.relative_humidity,
        )

        battery_mass = (
            self.config.propulsion.battery.series
            * self.config.propulsion.battery.parallel
            * self.config.propulsion.battery.cell_weight_g
            * 1.1
        )
        baseline_payload = self.config.components.payload_weight_g
        baseline_prop_mass = self.config.propulsion.motor.weight_g + battery_mass + 15.0

        assumed_weight_n = g_to_kg(900.0) * G
        structure_model = StructuresModel(
            geometry=geometry,
            structure=self.config.structure,
            components=self.config.components,
        )
        structure_result = structure_model.estimate(gross_weight_n=assumed_weight_n)

        total_mass = structure_result.total_empty_mass_g + baseline_prop_mass + baseline_payload
        weight_n = g_to_kg(total_mass) * G

        aero_model = AeroModel(geometry=geometry, airfoil=airfoil)
        stability = StabilityAnalyzer(aero_model=aero_model, stability=self.config.stability)

        try:
            trim_cruise = aero_model.trim_for_level_flight(
                weight_n=weight_n,
                speed_ms=cruise_speed,
                atmosphere=atmosphere,
                cg_x_fraction_mac=wing_cfg["cg_fraction_mac"],
            )
            trim_max = aero_model.trim_for_level_flight(
                weight_n=weight_n,
                speed_ms=max_speed,
                atmosphere=atmosphere,
                cg_x_fraction_mac=wing_cfg["cg_fraction_mac"],
            )
        except Exception:
            return None

        try:
            stability_result = stability.analyze(
                atmosphere=atmosphere,
                weight_n=weight_n,
                cruise_speed_ms=cruise_speed,
                min_speed_ms=max(8.0, cruise_speed * 0.60),
                max_speed_ms=max_speed,
                cg_fraction_mac=wing_cfg["cg_fraction_mac"],
            )
        except Exception:
            return None

        q_cruise = 0.5 * atmosphere.density_kgm3 * cruise_speed * cruise_speed
        q_max = 0.5 * atmosphere.density_kgm3 * max_speed * max_speed

        required_thrust_cruise = q_cruise * geometry.area_m2 * trim_cruise.cd
        required_thrust_max = q_max * geometry.area_m2 * trim_max.cd

        cl_max = max(p.cl for p in airfoil.polars) * (geometry.aspect_ratio / (geometry.aspect_ratio + 2.0))
        stall_speed = sqrt(2.0 * weight_n / (atmosphere.density_kgm3 * geometry.area_m2 * cl_max))

        wing_loading = total_mass / (geometry.area_m2 * 100.0)

        envelope = ThrustEnvelope(
            cruise_speed_ms=cruise_speed,
            max_speed_ms=max_speed,
            required_thrust_cruise_n=required_thrust_cruise,
            required_thrust_max_n=required_thrust_max,
            required_power_cruise_w=required_thrust_cruise * cruise_speed,
            required_power_max_w=required_thrust_max * max_speed,
        )

        constraints_ok = (
            stability.constraints_satisfied(stability_result)
            and stability_result.static_margin >= self.config.stability.min_static_margin
            and wing_loading < 50.0
            and stall_speed * 3.6 < 30.0
            and trim_cruise.ld > 8.0
            and structure_result.checks.stress_ok
            and structure_result.checks.deflection_ok
            and structure_result.checks.flutter_ok
        )

        score = self._score_candidate(
            feasible=constraints_ok,
            trim=trim_cruise,
            stability_result=stability_result,
            stall_speed_kmh=stall_speed * 3.6,
            wing_loading=wing_loading,
        )

        return WingCandidate(
            wingspan_m=geometry.wingspan_m,
            root_chord_m=geometry.root_chord_m,
            tip_chord_m=geometry.tip_chord_m,
            sweep_deg=geometry.sweep_deg,
            dihedral_deg=geometry.dihedral_deg,
            root_incidence_deg=geometry.root_incidence_deg,
            tip_incidence_deg=geometry.tip_incidence_deg,
            twist_deg=geometry.twist_deg,
            airfoil=airfoil_name,
            cg_fraction_mac=wing_cfg["cg_fraction_mac"],
            wing_area_m2=geometry.area_m2,
            aspect_ratio=geometry.aspect_ratio,
            wing_loading_gdm2=wing_loading,
            static_margin=stability_result.static_margin,
            lateral_stability_index=stability_result.lateral_stability_index,
            trim_elevon_deg=stability_result.trim_elevon_deg,
            cruise_ld=trim_cruise.ld,
            cruise_cd=trim_cruise.cd,
            stall_speed_kmh=stall_speed * 3.6,
            structural_mass_g=structure_result.structure_mass_g,
            total_mass_g=total_mass,
            envelope=envelope,
            feasible=constraints_ok,
            score=score,
        )

    @staticmethod
    def _score_candidate(
        feasible: bool,
        trim,
        stability_result,
        stall_speed_kmh: float,
        wing_loading: float,
    ) -> float:
        score = trim.ld * 10.0
        score -= abs(stability_result.trim_elevon_deg) * 0.6
        score -= max(0.0, stall_speed_kmh - 30.0) * 2.0
        score -= max(0.0, wing_loading - 45.0) * 1.5
        score += max(0.0, stability_result.static_margin - 0.08) * 100.0
        score += max(0.0, stability_result.lateral_stability_index - 0.6) * 40.0
        if not feasible:
            score -= 1000.0
        return score
